import { LegalShell, LegalSection } from '@/components/marketing/LegalDoc'

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" updated="July 2026 (draft)">
      <LegalSection num="01" title="Agreement to these terms">
        <p>
          These Terms of Service govern your use of Vindexa, an AI-powered study platform
          (the <strong>Service</strong>). By creating an account or using the Service, you agree to
          these terms. If you do not agree, do not use the Service.
        </p>
      </LegalSection>

      <LegalSection num="02" title="The service">
        <p>
          Vindexa lets you upload course materials (such as PDF, DOCX and PPTX files) or import them
          from Canvas LMS, and generates study tools from those materials: grounded question answering
          with citations, tutoring modes, quizzes, practice problems, mock exams, notes, flashcards,
          spaced review and readiness tracking.
        </p>
        <p>
          The Service is a study aid. It does not replace your coursework, your institution&rsquo;s
          official materials, or your own judgment.
        </p>
      </LegalSection>

      <LegalSection num="03" title="Accounts">
        <p>
          You must provide accurate information when creating an account and keep your credentials
          secure. You are responsible for all activity under your account. You must be old enough to
          form a binding contract in your jurisdiction to use the Service.
        </p>
      </LegalSection>

      <LegalSection num="04" title="Subscriptions and free trial">
        <p>
          The Service is offered as a single paid subscription with a free trial. No payment method is
          required to start a trial. When your trial ends, study features lock until you subscribe;
          your uploaded content remains stored and scoped to your account. Subscriptions are billed
          monthly and can be cancelled at any time, with access continuing through the end of the paid
          period. Pricing is a draft and may change before launch; active subscribers will be notified
          of any price change in advance.
        </p>
      </LegalSection>

      <LegalSection num="05" title="Your content">
        <p>
          You retain all rights to the materials you upload. You grant Vindexa a limited license to
          store and process your materials solely to provide the Service to you — for example,
          indexing your files so the Service can answer your questions and generate your study tools.
          We do not sell your content or use it to build products for other users.
        </p>
        <p>
          You are responsible for ensuring you have the right to upload the materials you use with the
          Service, including respecting your institution&rsquo;s policies on course content.
        </p>
      </LegalSection>

      <LegalSection num="06" title="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>use the Service to violate academic integrity policies, including during proctored exams;</li>
          <li>upload content you do not have the right to use, or content that is unlawful;</li>
          <li>attempt to access other users&rsquo; data or probe, scan or disrupt the Service;</li>
          <li>resell, scrape or programmatically extract the Service without permission.</li>
        </ul>
      </LegalSection>

      <LegalSection num="07" title="AI-generated content">
        <p>
          Answers, quizzes, notes and other outputs are generated by AI models (via the Anthropic API)
          from your materials. Outputs may contain errors or omissions even when citations are shown.
          Verify important information against your original materials before relying on it —
          especially before exams.
        </p>
      </LegalSection>

      <LegalSection num="08" title="Intellectual property">
        <p>
          The Service itself — its software, design and branding — belongs to Vindexa. These terms do
          not grant you any rights to it beyond the access needed to use the Service.
        </p>
      </LegalSection>

      <LegalSection num="09" title="Termination">
        <p>
          You may stop using the Service and delete your account at any time. We may suspend or
          terminate accounts that violate these terms. On termination, we will delete or de-identify
          your content within a reasonable period, except where retention is required by law.
        </p>
      </LegalSection>

      <LegalSection num="10" title="Disclaimers and limitation of liability">
        <p>
          The Service is provided <strong>&ldquo;as is&rdquo;</strong> without warranties of any kind, express or
          implied, including fitness for a particular purpose. To the maximum extent permitted by law,
          Vindexa&rsquo;s total liability arising out of the Service is limited to the amounts you paid
          for the Service in the twelve months before the claim. Vindexa is not liable for indirect,
          incidental or consequential damages, including academic outcomes.
        </p>
      </LegalSection>

      <LegalSection num="11" title="Changes to these terms">
        <p>
          We may update these terms as the Service evolves. If a change is material, we will notify
          you (for example, by email or an in-app notice) before it takes effect. Continued use after
          the effective date constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection num="12" title="Contact">
        <p>
          Questions about these terms: <a href="mailto:hello@vindexa.app" className="text-accent hover:text-accent-deep">hello@vindexa.app</a>.
        </p>
      </LegalSection>
    </LegalShell>
  )
}
